package col

// (c) Christian Maurer   v. 191107 - license see µU.go

func allColours() []Colour {
  return []Colour {
                   Brown(), // µU
                   BlackBrown(), // µU
                   DarkBrown(), // µU
                   MediumBrown(), // µU
                   LightBrown(), // µU
                   WhiteBrown(), // µU
                   BrownWhite(), // µU
                   Siena(), // µU
                   LightSiena(), // µU
                   RedBrown(), // µU
                   OliveBrown(), // µU
                   LightOliveBrown(), // µU
                   Umber(), // µU
                   DarkOchre(), // µU
                   Ochre(), // µU
                   LightOchre(), // µU
                   RoseBrown(), // µU
                   LightBeige(), // µU
                   Beige1(), // µU
                   VeryLightBrown(), // µU
                   BlackRed(), // µU
                   DarkRed(), // µU
                   Red(), // µU
                   FlashRed(), // µU
                   LightRed(), // µU
                   WhiteRed(), // µU
                   DarkRose(), // µU
                   Rose1(), // µU
                   LightRose(), // µU
                   PompejiRed(), // µU
                   CinnabarRed(), // µU
                   Carmine(), // µU
                   BrickRed(), // µU
                   FlashOrange(), // µU
                   DarkOrange(), // µU
                   Orange(), // µU
                   LightOrange(), // µU
                   WhiteOrange(), // µU
                   BloodOrange(), // µU
                   FlashYellow(), // µU
                   DarkYellow(), // µU
                   Yellow(), // µU
                   LightYellow(), // µU
                   WhiteYellow(), // µU
                   SandYellow(), // µU
                   LemonYellow(), // µU
                   FlashGreen(), // µU
                   BlackGreen(), // µU
                   DarkGreen(), // µU
                   Green(), // µU
                   LightGreen(), // µU
                   WhiteGreen(), // µU
                   BirchGreen(), // µU
                   GrassGreen(), // µU
                   OliveGreen(), // µU
                   LightOliveGreen(), // µU
                   YellowGreen(), // µU
                   MeadowGreen(), // µU
                   BlackCyan(), // µU
                   DarkCyan(), // µU
                   Cyan(), // µU
                   LightCyan(), // µU
                   WhiteCyan(), // µU
                   FlashCyan(), // µU
                   FlashBlue(), // µU
                   BlackBlue(), // µU
                   PrussianBlue(), // µU
                   DarkBlue(), // µU
                   Blue(), // µU
                   LightBlue(), // µU
                   WhiteBlue(), // µU
                   GentianBlue(), // µU
                   SkyBlue(), // µU
                   Ultramarine(), // µU
                   BlackMagenta(), // µU
                   DarkMagenta(), // µU
                   Magenta(), // µU
                   LightMagenta(), // µU
                   FlashMagenta(), // µU
                   WhiteMagenta(), // µU
                   Pink(), // µU
                   DeepPink(), // µU
                   BlackGray(), // µU
                   DarkGray(), // µU
                   Gray(), // µU
                   LightGray(), // µU
                   WhiteGray(), // µU
                   Silver(), // µU
                   White(), // µU
                   LightWhite(), // µU
                   Grünbeige(), // RAL
                   Beige(), // RAL
                   Sandgelb(), // RAL
                   Signalgelb(), // RAL
                   Goldgelb(), // RAL
                   Honiggelb(), // RAL
                   Maisgelb(), // RAL
                   Narzissengelb(), // RAL
                   Braunbeige(), // RAL
                   Zitronengelb(), // RAL
                   Perlweiß(), // RAL
                   Elfenbein(), // RAL
                   Hellelfenbein(), // RAL
                   Schwefelgelb(), // RAL
                   Safrangelb(), // RAL
                   Zinkgelb(), // RAL
                   Graubeige(), // RAL
                   Olivgelb(), // RAL
                   Rapsgelb(), // RAL
                   Verkehrsgelb(), // RAL
                   Ockergelb(), // RAL
                   Leuchtgelb(), // RAL
                   Currygelb(), // RAL
                   Melonengelb(), // RAL
                   Ginstergelb(), // RAL
                   Dahliengelb(), // RAL
                   Pastellgelb(), // RAL
                   Gelborange(), // RAL
                   Rotorange(), // RAL
                   Blutorange(), // RAL
                   Pastellorange(), // RAL
                   Reinorange(), // RAL
                   Leuchtorange(), // RAL
                   Leuchthellorange(), // RAL
                   Hellrotorange(), // RAL
                   Verkehrsorange(), // RAL
                   Signalorange(), // RAL
                   Tieforange(), // RAL
                   Lachsorange(), // RAL
                   Feuerrot(), // RAL
                   Signalrot(), // RAL
                   Karminrot(), // RAL
                   Rubinrot(), // RAL
                   Purpurrot(), // RAL
                   Weinrot(), // RAL
                   Schwarzrot(), // RAL
                   Oxidrot(), // RAL
                   Braunrot(), // RAL
                   Beigerot(), // RAL
                   Tomatenrot(), // RAL
                   Altrosa(), // RAL
                   Hellrosa(), // RAL
                   Korallenrot(), // RAL
                   Rose(), // RAL
                   Erdbeerrot(), // RAL
                   Verkehrsrot(), // RAL
                   Lachsrot(), // RAL
                   Leuchtrot(), // RAL
                   Leuchthellrot(), // RAL
                   Himbeerrot(), // RAL
                   Orientrot(), // RAL
                   Rotlila(), // RAL
                   Rotmagenta(), // RAL
                   Erikamagenta(), // RAL
                   Bordeauxmagenta(), // RAL
                   Blaulila(), // RAL
                   Verkehrspurpur(), // RAL
                   Purpurmagenta(), // RAL
                   Signalviolett(), // RAL
                   Pastellviolett(), // RAL
                   Telemagenta(), // RAL
                   Violettblau(), // RAL
                   Grünblau(), // RAL
                   Ultramarinblau(), // RAL
                   Saphirblau(), // RAL
                   Schwarzblau(), // RAL
                   Signalblau(), // RAL
                   Brillantblau(), // RAL
                   Graublau(), // RAL
                   Azurblau(), // RAL
                   Enzianblau(), // RAL
                   Stahlblau(), // RAL
                   Lichtblau(), // RAL
                   Kobaltblau(), // RAL
                   Taubenblau(), // RAL
                   Himmelblau(), // RAL
                   Verkehrsblau(), // RAL
                   Türkisblau(), // RAL
                   Capriblau(), // RAL
                   Ozeanblau(), // RAL
                   Wasserblau(), // RAL
                   Nachtblau(), // RAL
                   Fernblau(), // RAL
                   Pastellblau(), // RAL
                   Patinagrün(), // RAL
                   Smaragdgrün(), // RAL
                   Laubgrün(), // RAL
                   Olivgrün(), // RAL
                   Blaugrün(), // RAL
                   Moosgrün(), // RAL
                   Grauoliv(), // RAL
                   Flaschengrün(), // RAL
                   Braungrün(), // RAL
                   Tannengrün(), // RAL
                   Grasgrün(), // RAL
                   Resedagrün(), // RAL
                   Schwarzgrün(), // RAL
                   Schilfgrün(), // RAL
                   Gelboliv(), // RAL
                   Schwarzoliv(), // RAL
                   Cyangrün(), // RAL
                   Maigrün(), // RAL
                   Gelbgrün(), // RAL
                   Weißgrün(), // RAL
                   Chromoxidgrün(), // RAL
                   Blassgrün(), // RAL
                   Braunoliv(), // RAL
                   Verkehrsgrün(), // RAL
                   Farngrün(), // RAL
                   Opalgrün(), // RAL
                   Lichtgrün(), // RAL
                   Kieferngrün(), // RAL
                   Minzgrün(), // RAL
                   Signalgrün(), // RAL
                   Minttürkis(), // RAL
                   Pastelltürkis(), // RAL
                   Fehgrau(), // RAL
                   Silbergrau(), // RAL
                   Olivgrau(), // RAL
                   Moosgrau(), // RAL
                   Signalgrau(), // RAL
                   Mausgrau(), // RAL
                   Beigegrau(), // RAL
                   Khakigrau(), // RAL
                   Grüngrau(), // RAL
                   Zeltgrau(), // RAL
                   Eisengrau(), // RAL
                   Basaltgrau(), // RAL
                   Braungrau(), // RAL
                   Schiefergrau(), // RAL
                   Anthrazitgrau(), // RAL
                   Schwarzgrau(), // RAL
                   Umbragrau(), // RAL
                   Betongrau(), // RAL
                   Graphitgrau(), // RAL
                   Granitgrau(), // RAL
                   Steingrau(), // RAL
                   Blaugrau(), // RAL
                   Kieselgrau(), // RAL
                   Zementgrau(), // RAL
                   Gelbgrau(), // RAL
                   Lichtgrau(), // RAL
                   Platingrau(), // RAL
                   Staubgrau(), // RAL
                   Achatgrau(), // RAL
                   Quarzgrau(), // RAL
                   Fenstergrau(), // RAL
                   VerkehrsgrauA(), // RAL
                   VerkehrsgrauB(), // RAL
                   Seidengrau(), // RAL
                   Telegrau1(), // RAL
                   Telegrau2(), // RAL
                   Telegrau4(), // RAL
                   Grünbraun(), // RAL
                   Ockerbraun(), // RAL
                   Signalbraun(), // RAL
                   Lehmbraun(), // RAL
                   Kupferbraun(), // RAL
                   Rehbraun(), // RAL
                   Olivbraun(), // RAL
                   Nussbraun(), // RAL
                   Rotbraun(), // RAL
                   Sepiabraun(), // RAL
                   Kastanienbraun(), // RAL
                   Mahagonibraun(), // RAL
                   Schokoladenbraun(), // RAL
                   Graubraun(), // RAL
                   Schwarzbraun(), // RAL
                   Orangebraun(), // RAL
                   Beigebraun(), // RAL
                   Blassbraun(), // RAL
                   Terrabraun(), // RAL
                   Cremeweiß(), // RAL
                   Grauweiß(), // RAL
                   Signalweiß(), // RAL
                   Signalschwarz(), // RAL
                   Tiefschwarz(), // RAL
                   Aluminiumweiß(), // RAL
                   Aluminiumgrau(), // RAL
                   Reinweiß(), // RAL
                   Graphitschwarz(), // RAL
                   Verkehrsweiß(), // RAL
                   Verkehrsschwarz(), // RAL
                   Papyrusweiß(), // RAL
                   Brown1(), // X
                   Brown2(), // X
                   Brown3(), // X
                   Brown4(), // X
                   TRosyBrown(), // X
                   TSaddleBrown(), // X
                   TSandyBrown(), // X
                   TBrown(), // X
                   RosyBrown1(), // X
                   RosyBrown2(), // X
                   RosyBrown3(), // X
                   RosyBrown4(), // X
                   TChocolate(), // X
                   Salmon1(), // X
                   Salmon2(), // X
                   Salmon3(), // X
                   Salmon4(), // X
                   TSalmon(), // X
                   LightSalmon1(), // X
                   LightSalmon2(), // X
                   LightSalmon3(), // X
                   LightSalmon4(), // X
                   TLightSalmon(), // X
                   TDarkSalmon(), // X
                   Coral1(), // X
                   Coral2(), // X
                   Coral3(), // X
                   Coral4(), // X
                   TCoral(), // X
                   TLightCoral(), // X
                   Tan1(), // X
                   Tan2(), // X
                   Tan3(), // X
                   Tan4(), // X
                   TTan(), // X
                   Sienna1(), // X
                   Sienna2(), // X
                   Sienna3(), // X
                   Sienna4(), // X
                   TSienna(), // X
                   TPeru(), // X
                   Red1(), // X
                   Red2(), // X
                   Red3(), // X
                   Red4(), // X
                   Firebrick1(), // X
                   Firebrick2(), // X
                   Firebrick3(), // X
                   Firebrick4(), // X
                   TFirebrick(), // X
                   Crimson(), // X
                   TIndianRed(), // X
                   IndianRed1(), // X
                   IndianRed2(), // X
                   IndianRed3(), // X
                   IndianRed4(), // X
                   TTomato(), // X
                   Tomato1(), // X
                   Tomato2(), // X
                   Tomato3(), // X
                   Tomato4(), // X
                   OrangeRed1(), // X
                   OrangeRed2(), // X
                   OrangeRed3(), // X
                   OrangeRed4(), // X
                   TOrangeRed(), // X
                   DarkOrange1(), // X
                   DarkOrange2(), // X
                   DarkOrange3(), // X
                   DarkOrange4(), // X
                   TDarkOrange(), // X
                   Chocolate1(), // X
                   Chocolate2(), // X
                   Chocolate3(), // X
                   Chocolate4(), // X
                   Orange1(), // X
                   Orange2(), // X
                   Orange3(), // X
                   Orange4(), // X
                   TOrange(), // X
                   Yellow1(), // X
                   Yellow2(), // X
                   Yellow3(), // X
                   Yellow4(), // X
                   TYellow(), // X
                   Gold1(), // X
                   Gold2(), // X
                   Gold3(), // X
                   Gold4(), // X
                   TGold(), // X
                   LightGoldenrod1(), // X
                   LightGoldenrod2(), // X
                   LightGoldenrod3(), // X
                   LightGoldenrod4(), // X
                   TLightGoldenrod(), // X
                   TLightGoldenrodYellow(), // X
                   Goldenrod1(), // X
                   Goldenrod2(), // X
                   Goldenrod3(), // X
                   Goldenrod4(), // X
                   Tgoldenrod(), // X
                   DarkGoldenrod1(), // X
                   DarkGoldenrod2(), // X
                   DarkGoldenrod3(), // X
                   DarkGoldenrod4(), // X
                   TDarkGoldenrod(), // X
                   TPaleGoldenrod(), // X
                   TYellowGreen(), // X
                   TGreenYellow(), // X
                   Green1(), // X
                   Green2(), // X
                   Green3(), // X
                   Green4(), // X
                   XLightGreen(), // X
                   TGreen(), // X
                   TDarkGreen(), // X
                   Olive(), // X
                   DarkOliveGreen1(), // X
                   DarkOliveGreen2(), // X
                   DarkOliveGreen3(), // X
                   DarkOliveGreen4(), // X
                   TDarkOliveGreen(), // X
                   SeaGreen1(), // X
                   SeaGreen2(), // X
                   SeaGreen3(), // X
                   SeaGreen4(), // X
                   TSeaGreen(), // X
                   TLightSeaGreen(), // X
                   DarkSeaGreen1(), // X
                   DarkSeaGreen2(), // X
                   DarkSeaGreen3(), // X
                   DarkSeaGreen4(), // X
                   TDarkSeaGreen(), // X
                   TMediumSeaGreen(), // X
                   SpringGreen1(), // X
                   SpringGreen2(), // X
                   SpringGreen3(), // X
                   SpringGreen4(), // X
                   TSpringGreen(), // X
                   TMediumSpringGreen(), // X
                   PaleGreen1(), // X
                   PaleGreen2(), // X
                   PaleGreen3(), // X
                   PaleGreen4(), // X
                   TPaleGreen(), // X
                   TLawnGreen(), // X
                   TWebGreen(), // X
                   TLimeGreen(), // X
                   TForestGreen(), // X
                   Chartreuse1(), // X
                   Chartreuse2(), // X
                   Chartreuse3(), // X
                   Chartreuse4(), // X
                   TChartreuse(), // X
                   OliveDrab1(), // X
                   OliveDrab2(), // X
                   OliveDrab3(), // X
                   OliveDrab4(), // X
                   TOliveDrab(), // X
                   TLime(), // X
                   LightCyan1(), // X
                   LightCyan2(), // X
                   LightCyan3(), // X
                   LightCyan4(), // X
                   TLightCyan(), // X
                   Cyan1(), // X
                   Cyan2(), // X
                   Cyan3(), // X
                   Cyan4(), // X
                   TCyan(), // X
                   XDarkCyan(), // X
                   PaleTurquoise(), // X
                   PaleTurquoise1(), // X
                   PaleTurquoise2(), // X
                   PaleTurquoise3(), // X
                   PaleTurquoise4(), // X
                   Turquoise1(), // X
                   Turquoise2(), // X
                   Turquoise3(), // X
                   Turquoise4(), // X
                   TTurquoise(), // X
                   DarkTurquoise(), // X
                   MediumTurquoise(), // X
                   Navy(), // X
                   MidnightBlue(), // X
                   XDarkBlue(), // X
                   TLightBlue1(), // X
                   TLightBlue2(), // X
                   TLightBlue3(), // X
                   TLightBlue4(), // X
                   XLightBlue(), // X
                   SlateBlue(), // X
                   DarkSlateBlue(), // X
                   MediumSlateBlue(), // X
                   LightSlateBlue(), // X
                   TSlateBlue1(), // X
                   TSlateBlue2(), // X
                   TSlateBlue3(), // X
                   TSlateBlue4(), // X
                   MediumBlue(), // X
                   RoyalBlue(), // X
                   SteelBlue(), // X
                   LightSteelBlue(), // X
                   PowderBlue(), // X
                   TRoyalBlue1(), // X
                   TRoyalBlue2(), // X
                   TRoyalBlue3(), // X
                   TRoyalBlue4(), // X
                   DodgerBlue(), // X
                   TDodgerBlue1(), // X
                   TDodgerBlue2(), // X
                   TDodgerBlue3(), // X
                   TDodgerBlue4(), // X
                   TSkyBlue1(), // X
                   TSkyBlue2(), // X
                   TSkyBlue3(), // X
                   TSkyBlue4(), // X
                   XSkyBlue(), // X
                   LightSkyBlue(), // X
                   TLightSkyBlue1(), // X
                   TLightSkyBlue2(), // X
                   TLightSkyBlue3(), // X
                   TLightSkyBlue4(), // X
                   DeepSkyBlue(), // X
                   TDeepSkyBlue1(), // X
                   TDeepSkyBlue2(), // X
                   TDeepSkyBlue3(), // X
                   TDeepSkyBlue4(), // X
                   TSteelBlue1(), // X
                   TSteelBlue2(), // X
                   TSteelBlue3(), // X
                   TSteelBlue4(), // X
                   TLightSteelBlue1(), // X
                   TLightSteelBlue2(), // X
                   TLightSteelBlue3(), // X
                   TLightSteelBlue4(), // X
                   CadetBlue1(), // X
                   CadetBlue2(), // X
                   CadetBlue3(), // X
                   CadetBlue4(), // X
                   TCadetBlue(), // X
                   AliceBlue(), // X
                   CornflowerBlue(), // X
                   TAqua(), // X
                   Aquamarine1(), // X
                   Aquamarine2(), // X
                   Aquamarine3(), // X
                   Aquamarine4(), // X
                   TAquamarine(), // X
                   TMediumAquamarine(), // X
                   Teal(), // X
                   TBlueViolet(), // X
                   PaleVioletRed1(), // X
                   PaleVioletRed2(), // X
                   PaleVioletRed3(), // X
                   PaleVioletRed4(), // X
                   TPaleVioletRed(), // X
                   VioletRed1(), // X
                   VioletRed2(), // X
                   VioletRed3(), // X
                   VioletRed4(), // X
                   TVioletRed(), // X
                   TMediumVioletRed(), // X
                   TViolet(), // X
                   TDarkViolet(), // X
                   Magenta1(), // X
                   Magenta2(), // X
                   Magenta3(), // X
                   Magenta4(), // X
                   TMagenta(), // X
                   XDarkMagenta(), // X
                   Indigo(), // X
                   Purple1(), // X
                   Purple2(), // X
                   Purple3(), // X
                   Purple4(), // X
                   TPurple(), // X
                   MediumPurple1(), // X
                   MediumPurple2(), // X
                   MediumPurple3(), // X
                   MediumPurple4(), // X
                   TMediumPurple(), // X
                   TWebPurple(), // X
                   RebeccaPurple(), // X
                   Maroon1(), // X
                   Maroon2(), // X
                   Maroon3(), // X
                   Maroon4(), // X
                   TMaroon(), // X
                   TWebMaroon(), // X
                   Orchid1(), // X
                   Orchid2(), // X
                   Orchid3(), // X
                   Orchid4(), // X
                   TOrchid(), // X
                   MediumOrchid1(), // X
                   MediumOrchid2(), // X
                   MediumOrchid3(), // X
                   MediumOrchid4(), // X
                   TMediumOrchid(), // X
                   DarkOrchid1(), // X
                   DarkOrchid2(), // X
                   DarkOrchid3(), // X
                   DarkOrchid4(), // X
                   TDarkOrchid(), // X
                   Plum1(), // X
                   Plum2(), // X
                   Plum3(), // X
                   Plum4(), // X
                   TPlum(), // X
                   DeepPink1(), // X
                   DeepPink2(), // X
                   DeepPink3(), // X
                   DeepPink4(), // X
                   TDeepPink(), // X
                   HotPink1(), // X
                   HotPink2(), // X
                   HotPink3(), // X
                   HotPink4(), // X
                   THotPink(), // X
                   Pink1(), // X
                   Pink2(), // X
                   Pink3(), // X
                   Pink4(), // X
                   TPink(), // X
                   LightPink1(), // X
                   LightPink2(), // X
                   LightPink3(), // X
                   LightPink4(), // X
                   TLightPink(), // X
                   Snow(), // X
                   TSnow1(), // X
                   TSnow2(), // X
                   TSnow3(), // X
                   TSnow4(), // X
                   LightYellow1(), // X
                   LightYellow2(), // X
                   LightYellow3(), // X
                   LightYellow4(), // X
                   TLightYellow(), // X
                   Azure(), // X
                   TAzure1(), // X
                   TAzure2(), // X
                   TAzure3(), // X
                   TAzure4(), // X
                   GhostWhite(), // X
                   WhiteSmoke(), // X
                   Gainsboro(), // X
                   FloralWhite(), // X
                   OldLace(), // X
                   Linen(), // X
                   AntiqueWhite(), // X
                   TAntiqueWhite1(), // X
                   TAntiqueWhite2(), // X
                   TAntiqueWhite3(), // X
                   TAntiqueWhite4(), // X
                   PapayaWhip(), // X
                   BlanchedAlmond(), // X
                   NavajoWhite(), // X
                   TNavajoWhite1(), // X
                   TNavajoWhite2(), // X
                   TNavajoWhite3(), // X
                   TNavajoWhite4(), // X
                   Moccasin(), // X
                   Cornsilk(), // X
                   TCornsilk1(), // X
                   TCornsilk2(), // X
                   TCornsilk3(), // X
                   TCornsilk4(), // X
                   Ivory(), // X
                   TIvory1(), // X
                   TIvory2(), // X
                   TIvory3(), // X
                   TIvory4(), // X
                   Honeydew(), // X
                   THoneydew1(), // X
                   THoneydew2(), // X
                   THoneydew3(), // X
                   THoneydew4(), // X
                   MintCream(), // X
                   TBeige(), // X
                   Seashell(), // X
                   TSeashell1(), // X
                   TSeashell2(), // X
                   TSeashell3(), // X
                   TSeashell4(), // X
                   Bisque(), // X
                   TBisque1(), // X
                   TBisque2(), // X
                   TBisque3(), // X
                   TBisque4(), // X
                   PeachPuff(), // X
                   TPeachPuff1(), // X
                   TPeachPuff2(), // X
                   TPeachPuff3(), // X
                   TPeachPuff4(), // X
                   LemonChiffon(), // X
                   TLemonChiffon1(), // X
                   TLemonChiffon2(), // X
                   TLemonChiffon3(), // X
                   TLemonChiffon4(), // X
                   Lavender(), // X
                   LavenderBlush(), // X
                   TLavenderBlush1(), // X
                   TLavenderBlush2(), // X
                   TLavenderBlush3(), // X
                   TLavenderBlush4(), // X
                   MistyRose(), // X
                   TMistyRose1(), // X
                   TMistyRose2(), // X
                   TMistyRose3(), // X
                   TMistyRose4(), // X
                   Khaki1(), // X
                   Khaki2(), // X
                   Khaki3(), // X
                   Khaki4(), // X
                   TKhaki(), // X
                   TDarkKhaki(), // X
                   Burlywood1(), // X
                   Burlywood2(), // X
                   Burlywood3(), // X
                   Burlywood4(), // X
                   TBurlywood(), // X
                   Wheat1(), // X
                   Wheat2(), // X
                   Wheat3(), // X
                   Wheat4(), // X
                   TWheat(), // X
                   Black(),
                   Gray1(), Gray2(), Gray3(), Gray4(), Gray5(), // X
                   Gray6(), Gray7(), Gray8(), Gray9(), Gray10(), // X
                   Gray11(), Gray12(), Gray13(), Gray14(), Gray15(), // X
                   Gray16(), Gray17(), Gray18(), Gray19(), Gray20(), // X
                   Gray21(), Gray22(), Gray23(), Gray24(), Gray25(), // X
                   Gray26(), Gray27(), Gray28(), Gray29(), Gray30(), // X
                   Gray31(), Gray32(), Gray33(), Gray34(), Gray35(), // X
                   Gray36(), Gray37(), Gray38(), Gray39(), Gray40(), // X
                   Gray41(), Gray42(), Gray43(), Gray44(), Gray45(), // X
                   Gray46(), Gray47(), Gray48(), Gray49(), Gray50(), // X
                   Gray51(), Gray52(), Gray53(), Gray54(), Gray55(), // X
                   Gray56(), Gray57(), Gray58(), Gray59(), Gray60(), // X
                   Gray61(), Gray62(), Gray63(), Gray64(), Gray65(), // X
                   Gray66(), Gray67(), Gray68(), Gray69(), Gray70(), // X
                   Gray71(), Gray72(), Gray73(), Gray74(), Gray75(), // X
                   Gray76(), Gray77(), Gray78(), Gray79(), Gray80(), // X
                   Gray81(), Gray82(), Gray83(), Gray84(), Gray85(), // X
                   Gray86(), Gray87(), Gray88(), Gray89(), Gray90(), // X
                   Gray91(), Gray92(), Gray93(), Gray94(), Gray95(), // X
                   Gray96(), Gray97(), Gray98(), Gray99(), Gray100(), // X
                   Thistle1(), // X
                   Thistle2(), // X
                   Thistle3(), // X
                   Thistle4(), // X
                   Tthistle(), // X
                   LightSlateGray(), // X
                   DarkSlateGray(), // X
                   DarkSlateGray1(), // X
                   DarkSlateGray2(), // X
                   DarkSlateGray3(), // X
                   DarkSlateGray4(), // X
                   SlateGray(), // X
                   TSlateGray1(), // X
                   TSlateGray2(), // X
                   TSlateGray3(), // X
                   TSlateGray4(), // X
                   DimGray(), // X
                   WebGray(), // X
                   XDarkGray(), // X
                   XSilver(), // X
                  }
}
