package col

// (c) Christian Maurer   v. 230401 - license see µU.go

func allColours() []Colour {
  return []Colour {FlashBrown(), BlackBrown(), DarkBrown(), Brown(),
                   LightBrown(), WhiteBrown(),
                   DarkOchre(), Ochre(), LightOchre(),
                   FlashRed(), BlackRed(), DarkRed(), Red(),
                   LightRed(), WhiteRed(), Carmine(), PompejiRed(),
                   BrickRed(), CinnabarRed(), Siena(), LightSiena(),
                   DarkRose(), LightRose(), WhiteRose(),
                   FlashOrange(), BlackOrange(), DarkOrange(), Orange(),
                   LightOrange(), WhiteOrange(),
                   FlashYellow(), BlackYellow(), DarkYellow(), Yellow(),
                   LightYellow(), WhiteYellow(),
                   FlashGreen(), BlackGreen(), DarkGreen(), Green(),
                   LightGreen(), WhiteGreen(),
                   GrassGreen(), Umber(), OliveGreen(), LightOliveGreen(),
                   YellowGreen(), MeadowGreen(),
                   FlashCyan(), BlackCyan(), DarkCyan(), Cyan(),
                   LightCyan(), WhiteCyan(),
                   FlashBlue(), BlackBlue(), DarkBlue(), Blue(),
                   LightBlue(), WhiteBlue(), PrussianBlue(), GentianBlue(),
                   SkyBlue(), SkyLightBlue(), Ultramarine(), UltramarinBlue(),
                   FlashMagenta(), BlackMagenta(), DarkMagenta(), Magenta(),
                   LightMagenta(), WhiteMagenta(), Pink(), DeepPink(),
                   Black(),
                   FlashGray(), BlackGray(), DarkGray(), Gray(),
                   LightGray(), WhiteGray(),
                   Silver(),
                   FlashWhite(), White(),
// RAL-Farben:
                   Grünbeige(), Beige(), Sandgelb(), Signalgelb(),
                   Goldgelb(), Honiggelb(), Maisgelb(), Narzissengelb(),
                   Braunbeige(), Zitronengelb(), Perlweiß(), Elfenbein(),
                   Hellelfenbein(), Schwefelgelb(), Safrangelb(), Zinkgelb(),
                   Graubeige(), Olivgelb(), Rapsgelb(), Verkehrsgelb(),
                   Ockergelb(), Leuchtgelb(), Currygelb(), Melonengelb(),
                   Ginstergelb(), Dahliengelb(), Pastellgelb(), Perlbeige(),
                   Perlgold(), Sonnengelb(),
                   Gelborange(), Rotorange(), Blutorange(), Pastellorange(),
                   Reinorange(), Leuchtorange(), Leuchthellorange(), Hellrotorange(),
                   Verkehrsorange(), Signalorange(), Tieforange(), Lachsorange(),
                   Perlorange(), RALorange(),
                   Feuerrot(), Signalrot(), Karminrot(), Rubinrot(),
                   Purpurrot(), Weinrot(), Schwarzrot(), Oxidrot(),
                   Braunrot(), Beigerot(), Tomatenrot(), Altrosa(),
                   Hellrosa(), Korallenrot(), Rose(), Erdbeerrot(),
                   Verkehrsrot(), Lachsrot(), Leuchtrot(), Leuchthellrot(),
                   Himbeerrot(), Reinrot(), Orientrot(), Perlrubinrot(),
                   Perlrosa(),
                   Rotlila(), Rotviolett(), Erikaviolett(), Bordeauxviolett(),
                   Blaulila(), Verkehrspurpur(), Purpurviolett(), Signalviolett(),
                   Pastellviolett(), Telemagenta(), Perlviolett(), Perlbrombeer(),
                   Violettblau(), Grünblau(), Ultramarinblau(), Saphirblau(),
                   Schwarzblau(), Signalblau(), Brillantblau(), Graublau(),
                   Azurblau(), Enzianblau(), Stahlblau(), Lichtblau(),
                   Kobaltblau(), Taubenblau(), Himmelblau(), Verkehrsblau(),
                   Türkisblau(), Capriblau(), Ozeanblau(), Wasserblau(),
                   Nachtblau(), Fernblau(), Pastellblau(), Perlenzian(),
                   Perlnachtblau(),
                   Patinagrün(), Smaragdgrün(), Laubgrün(), Olivgrün(),
                   Blaugrün(), Moosgrün(), Grauoliv(), Flaschengrün(),
                   Braungrün(), Tannengrün(), Grasgrün(), Resedagrün(),
                   Schwarzgrün(), Schilfgrün(), Gelboliv(), Schwarzoliv(),
                   Türkisgrün(), Maigrün(), Gelbgrün(), Weißgrün(),
                   Chromoxidgrün(), Blassgrün(), Braunoliv(), Verkehrsgrün(),
                   Farngrün(), Opalgrün(), Lichtgrün(), Kieferngrün(),
                   Minzgrün(), Signalgrün(), Minttürkis(), Pastelltürkis(),
                   Perlgrün(), Perlopalgrün(), Reingrün(), Leuchtgrün(),
                   Fasergrün(),
                   Fehgrau(), Silbergrau(), Olivgrau(), Moosgrau(),
                   Signalgrau(), Mausgrau(), Beigegrau(), Khakigrau(),
                   Grüngrau(), Zeltgrau(), Eisengrau(), Basaltgrau(),
                   Braungrau(), Schiefergrau(), Anthrazitgrau(), Schwarzgrau(),
                   Umbragrau(), Betongrau(), Graphitgrau(), Granitgrau(),
                   Steingrau(), Blaugrau(), Kieselgrau(), Zementgrau(),
                   Gelbgrau(), Lichtgrau(), Platingrau(), Staubgrau(),
                   Achatgrau(), Quarzgrau(), Fenstergrau(), VerkehrsgrauA(),
                   VerkehrsgrauB(), Seidengrau(), Telegrau1(), Telegrau2(),
                   Telegrau4(), Perlmausgrau(),
                   Grünbraun(), Ockerbraun(), Signalbraun(), Lehmbraun(),
                   Kupferbraun(), Rehbraun(), Olivbraun(), Nussbraun(),
                   Rotbraun(), Sepiabraun(), Kastanienbraun(), Mahagonibraun(),
                   Schokoladenbraun(), Graubraun(), Schwarzbraun(), Orangebraun(),
                   Beigebraun(), Blassbraun(), Terrabraun(), Perlkupfer(),
                   Cremeweiß(), Grauweiß(), Signalweiß(), Signalschwarz(),
                   Tiefschwarz(), Weißaluminium(), Graualuminium(), Reinweiß(),
                   Graphitschwarz(), Reinraumweiß(), Verkehrsweiß(), Verkehrsschwarz(),
                   Papyrusweiß(), Perlhellgrau(), Perldunkelgrau(),
                   }
}
