package col

// (c) Christian Maurer   v. 201026 - license see µU.go

func Grünbeige() Colour {        return new3 ("Grünbeige",        214, 199, 148) }
func Beige() Colour {            return new3 ("Beige",            217, 186, 140) }
func Sandgelb() Colour {         return new3 ("Sandgelb",         214, 176, 117) }
func Signalgelb() Colour {       return new3 ("Signalgelb ",      252, 163,  41) }
func Goldgelb() Colour {         return new3 ("Goldgelb",         227, 150,  36) }
func Honiggelb() Colour {        return new3 ("Honiggelb",        201, 135,  33) }
func Maisgelb() Colour {         return new3 ("Maisgelb",         224, 130,  31) }
func Narzissengelb() Colour {    return new3 ("Narzissengelb",    227, 122,  31) }
func Braunbeige() Colour {       return new3 ("Braunbeige",       173, 122,  79) }
func Zitronengelb() Colour {     return new3 ("Zitronengelb",     227, 184,  56) }
func Perlweiß() Colour {         return new3 ("Perlweiß",         255, 245, 227) }
func Elfenbein() Colour {        return new3 ("Elfenbein",        240, 214, 171) }
func Hellelfenbein() Colour {    return new3 ("Hellelfenbein",    252, 235, 204) }
func Schwefelgelb() Colour {     return new3 ("Schwefelgelb",     255, 245,  66) }
func Safrangelb() Colour {       return new3 ("Safrangelb",       255, 171,  89) }
func Zinkgelb() Colour {         return new3 ("Zinkgelb",         255, 214,  77) }
func Graubeige() Colour {        return new3 ("Graubeige",        163, 140, 122) }
func Olivgelb() Colour {         return new3 ("Olivgelb",         156, 143,  97) }
func Rapsgelb() Colour {         return new3 ("Rapsgelb",         252, 189,  31) }
func Verkehrsgelb() Colour {     return new3 ("Verkehrsgelb",     252, 184,  33) }
func Ockergelb() Colour {        return new3 ("Ockergelb",        181, 140,  79) }
func Leuchtgelb() Colour {       return new3 ("Leuchtgelb",       255, 255,  10) }
func Currygelb() Colour {        return new3 ("Currygelb",        153, 117,  33) }
func Melonengelb() Colour {      return new3 ("Melonengelb",      255, 140,  26) }
func Ginstergelb() Colour {      return new3 ("Ginstergelb",      227, 163,  41) }
func Dahliengelb() Colour {      return new3 ("Dahliengelb",      255, 148,  54) }
func Pastellgelb() Colour {      return new3 ("Pastellgelb",      247, 153,  92) }
func Gelborange() Colour {       return new3 ("Gelborange",       224,  94,  31) }
func Rotorange() Colour {        return new3 ("Rotorange",        186,  46,  33) }
func Blutorange() Colour {       return new3 ("Blutorange",       204,  36,  28) }
func Pastellorange() Colour {    return new3 ("Pastellorange",    255,  99,  54) }
func Reinorange() Colour {       return new3 ("Reinorange",       242,  59,  28) }
func Leuchtorange() Colour {     return new3 ("Leuchtorange",     252,  28,  20) }
func Leuchthellorange() Colour { return new3 ("Leuchthellorange", 255, 117,  33) }
func Hellrotorange() Colour {    return new3 ("Hellrotorange",    250,  79,  41) }
func Verkehrsorange() Colour {   return new3 ("Verkehrsorange",   235,  59,  28) }
func Signalorange() Colour {     return new3 ("Signalorange",     212,  69,  41) }
func Tieforange() Colour {       return new3 ("Tieforange",       237,  92,  41) }
func Lachsorange() Colour {      return new3 ("Lachsorange",      222,  82,  71) }
func Feuerrot() Colour {         return new3 ("Feuerrot",         171,  31,  28) }
func Signalrot() Colour {        return new3 ("Signalrot",        163,  23,  26) }
func Karminrot() Colour {        return new3 ("Karminrot",        163,  26,  26) }
func Rubinrot() Colour {         return new3 ("Rubinrot",         138,  18,  20) }
func Purpurrot() Colour {        return new3 ("Purpurrot",        105,  15,  20) }
func Weinrot() Colour {          return new3 ("Weinrot",           79,  18,  26) }
func Schwarzrot() Colour {       return new3 ("Schwarzrot",        46,  18,  26) }
func Oxidrot() Colour {          return new3 ("Oxidrot",           94,  33,  33) }
func Braunrot() Colour {         return new3 ("Braunrot",         120,  20,  23) }
func Beigerot() Colour {         return new3 ("Beigerot",         204, 130, 115) }
func Tomatenrot() Colour {       return new3 ("Tomatenrot",       150,  31,  28) }
func Altrosa() Colour {          return new3 ("Altrosa",          217, 102, 117) }
func Hellrosa() Colour {         return new3 ("Hellrosa",         232, 156, 181) }
func Korallenrot() Colour {      return new3 ("Korallenrot",      166,  36,  38) }
func Rose() Colour {             return new3 ("Rose",             209,  54,  84) }
func Erdbeerrot() Colour {       return new3 ("Erdbeerrot",       207,  41,  66) }
func Verkehrsrot() Colour {      return new3 ("Verkehrsrot",      199,  23,  18) }
func Lachsrot() Colour {         return new3 ("Lachsrot",         217,  89,  79) }
func Leuchtrot() Colour {        return new3 ("Leuchtrot",        252,  10,  28) }
func Leuchthellrot() Colour {    return new3 ("Leuchthellrot",    252,  20,  20) }
func Himbeerrot() Colour {       return new3 ("Himbeerrot",       181,  18,  51) }
func Orientrot() Colour {        return new3 ("Orientrot",        166,  28,  46) }
func Rotlila() Colour {          return new3 ("Rotlila",          130,  64, 128) }
func Rotmagenta() Colour {       return new3 ("Rotmagenta",       143,  38,  64) }
func Erikamagenta() Colour {     return new3 ("Erikamagenta",     201,  56, 140) }
func Bordeauxmagenta() Colour {  return new3 ("Bordeauxmagenta",   92,   8,  43) }
func Blaulila() Colour {         return new3 ("Blaulila",          99,  61, 156) }
func Verkehrspurpur() Colour {   return new3 ("Verkehrspurpur",   145,  15, 102) }
func Purpurmagenta() Colour {    return new3 ("Purpurmagenta",     56,  10,  46) }
func Signalviolett() Colour {    return new3 ("Signalviolett",    125,  31, 122) }
func Pastellviolett() Colour {   return new3 ("Pastellviolett",   158, 115, 148) }
func Telemagenta() Colour {      return new3 ("Telemagenta",      191,  23, 115) }
func Violettblau() Colour {      return new3 ("Violettblau",       23,  51, 107) }
func Grünblau() Colour {         return new3 ("Grünblau",          10,  51,  84) }
func Ultramarinblau() Colour {   return new3 ("Ultramarinblau",     0,  15, 117) }
func Saphirblau() Colour {       return new3 ("Saphirblau",         0,  23,  69) }
func Schwarzblau() Colour {      return new3 ("Schwarzblau",        3,  13,  31) }
func Signalblau() Colour {       return new3 ("Signalblau",         0,  46, 122) }
func Brillantblau() Colour {     return new3 ("Brillantblau",      38,  79, 135) }
func Graublau() Colour {         return new3 ("Graublau",          26,  41,  56) }
func Azurblau() Colour {         return new3 ("Azurblau",          23,  69, 112) }
func Enzianblau() Colour {       return new3 ("Enzianblau",         0,  43, 112) }
func Stahlblau() Colour {        return new3 ("Stahlblau",          3,  20,  46) }
func Lichtblau() Colour {        return new3 ("Lichtblau",         41, 115, 184) }
func Kobaltblau() Colour {       return new3 ("Kobaltblau",         0,  18,  69) }
func Taubenblau() Colour {       return new3 ("Taubenblau",        77, 105, 153) }
func Himmelblau() Colour {       return new3 ("Himmelblau",        23,  97, 171) }
func Verkehrsblau() Colour {     return new3 ("Verkehrsblau",       0,  59, 128) }
func Türkisblau() Colour {       return new3 ("Türkisblau",        56, 148, 130) }
func Capriblau() Colour {        return new3 ("Capriblau",         10,  66, 120) }
func Ozeanblau() Colour {        return new3 ("Ozeanblau",          5,  51,  51) }
func Wasserblau() Colour {       return new3 ("Wasserblau",        26, 122,  99) }
func Nachtblau() Colour {        return new3 ("Nachtblau",          0,   8,  79) }
func Fernblau() Colour {         return new3 ("Fernblau",          46,  82, 143) }
func Pastellblau() Colour {      return new3 ("Pastellblau",       87, 140, 181) }
func Patinagrün() Colour {       return new3 ("Patinagrün",        51, 120,  84) }
func Smaragdgrün() Colour {      return new3 ("Smaragdgrün",       38, 102,  41) }
func Laubgrün() Colour {         return new3 ("Laubgrün",          38,  87,  33) }
func Olivgrün() Colour {         return new3 ("Olivgrün",          61,  69,  46) }
func Blaugrün() Colour {         return new3 ("Blaugrün",          13,  59,  46) }
func Moosgrün() Colour {         return new3 ("Moosgrün",          10,  56,  31) }
func Grauoliv() Colour {         return new3 ("Grauoliv",          41,  43,  36) }
func Flaschengrün() Colour {     return new3 ("Flaschengrün",      28,  38,  23) }
func Braungrün() Colour {        return new3 ("Braungrün",         33,  33,  26) }
func Tannengrün() Colour {       return new3 ("Tannengrün",        23,  41,  28) }
func Grasgrün() Colour {         return new3 ("Grasgrün",          54, 105,  38) }
func Resedagrün() Colour {       return new3 ("Resedagrün",        94, 125,  79) }
func Schwarzgrün() Colour {      return new3 ("Schwarzgrün",       31,  46,  43) }
func Schilfgrün() Colour {       return new3 ("Schilfgrün",       117, 115,  79) }
func Gelboliv() Colour {         return new3 ("Gelboliv",          51,  48,  38) }
func Schwarzoliv() Colour {      return new3 ("Schwarzoliv",       41,  43,  38) }
func Cyangrün() Colour {         return new3 ("Cyangrün",          15, 112,  51) }
func Maigrün() Colour {          return new3 ("Maigrün",           64, 130,  54) }
func Gelbgrün() Colour {         return new3 ("Gelbgrün",          79, 168,  51) }
func Weißgrün() Colour {         return new3 ("Weißgrün",         191, 227, 186) }
func Chromoxidgrün() Colour {    return new3 ("Chromoxidgrün",     38,  56,  41) }
func Blassgrün() Colour {        return new3 ("Blassgrün",        133, 166, 122) }
func Braunoliv() Colour {        return new3 ("Braunoliv",         43,  38,  28) }
func Verkehrsgrün() Colour {     return new3 ("Verkehrsgrün",      36, 145,  64) }
func Farngrün() Colour {         return new3 ("Farngrün",          74, 110,  51) }
func Opalgrün() Colour {         return new3 ("Opalgrün",          10,  92,  51) }
func Lichtgrün() Colour {        return new3 ("Lichtgrün",        125, 204, 189) }
func Kieferngrün() Colour {      return new3 ("Kieferngrün",       38,  74,  51) }
func Minzgrün() Colour {         return new3 ("Minzgrün",          18, 120,  38) }
func Signalgrün() Colour {       return new3 ("Signalgrün",        41, 138,  64) }
func Minttürkis() Colour {       return new3 ("Minttürkis",        66, 140, 120) }
func Pastelltürkis() Colour {    return new3 ("Pastelltürkis",      0,   0,   0) } // XXX falsch
func Fehgrau() Colour {          return new3 ("Fehgrau",          115, 133, 145) }
func Silbergrau() Colour {       return new3 ("Silbergrau",       135, 148, 166) }
func Olivgrau() Colour {         return new3 ("Olivgrau",         122, 117,  97) }
func Moosgrau() Colour {         return new3 ("Moosgrau",         112, 112,  97) }
func Signalgrau() Colour {       return new3 ("Signalgrau",       156, 156, 166) }
func Mausgrau() Colour {         return new3 ("Mausgrau",          97, 105, 105) }
func Beigegrau() Colour {        return new3 ("Beigegrau",        107,  97,  87) }
func Khakigrau() Colour {        return new3 ("Khakigrau",        105,  84,  56) }
func Grüngrau() Colour {         return new3 ("Grüngrau",          77,  82,  74) }
func Zeltgrau() Colour {         return new3 ("Zeltgrau",          74,  79,  74) }
func Eisengrau() Colour {        return new3 ("Eisengrau",         64,  74,  84) }
func Basaltgrau() Colour {       return new3 ("Basaltgrau",        74,  84,  89) }
func Braungrau() Colour {        return new3 ("Braungrau",         71,  66,  56) }
func Schiefergrau() Colour {     return new3 ("Schiefergrau",      61,  66,  82) }
func Anthrazitgrau() Colour {    return new3 ("Anthrazitgrau",     38,  46,  56) }
func Schwarzgrau() Colour {      return new3 ("Schwarzgrau",       26,  33,  41) }
func Umbragrau() Colour {        return new3 ("Umbragrau",         61,  61,  59) }
func Betongrau() Colour {        return new3 ("Betongrau",        122, 125, 117) }
func Graphitgrau() Colour {      return new3 ("Graphitgrau",       48,  56,  69) }
func Granitgrau() Colour {       return new3 ("Granitgrau",        38,  51,  56) }
func Steingrau() Colour {        return new3 ("Steingrau",        145, 143, 135) }
func Blaugrau() Colour {         return new3 ("Blaugrau",          77,  92, 107) }
func Kieselgrau() Colour {       return new3 ("Kieselgrau",       189, 186, 171) }
func Zementgrau() Colour {       return new3 ("Zementgrau",       122, 130, 117) }
func Gelbgrau() Colour {         return new3 ("Gelbgrau",         143, 135, 112) }
func Lichtgrau() Colour {        return new3 ("Lichtgrau",        212, 217, 219) }
func Platingrau() Colour {       return new3 ("Platingrau",       158, 150, 156) }
func Staubgrau() Colour {        return new3 ("Staubgrau",        122, 125, 128) }
func Achatgrau() Colour {        return new3 ("Achatgrau",        186, 189, 186) }
func Quarzgrau() Colour {        return new3 ("Quarzgrau",         97,  94,  89) }
func Fenstergrau() Colour {      return new3 ("Fenstergrau",      158, 163, 176) }
func VerkehrsgrauA() Colour {    return new3 ("VerkehrsgrauA",    143, 150, 153) }
func VerkehrsgrauB() Colour {    return new3 ("VerkehrsgrauB",     64,  69,  69) }
func Seidengrau() Colour {       return new3 ("Seidengrau",       194, 191, 184) }
func Telegrau1() Colour {        return new3 ("Telegrau1",        143, 148, 158) }
func Telegrau2() Colour {        return new3 ("Telegrau2",        120, 130, 140) }
func Telegrau4() Colour {        return new3 ("Telegrau4",        217, 214, 219) }
func Grünbraun() Colour {        return new3 ("Grünbraun",        125,  92,  56) }
func Ockerbraun() Colour {       return new3 ("Ockerbraun",       145,  82,  46) }
func Signalbraun() Colour {      return new3 ("Signalbraun",      110,  59,  48) }
func Lehmbraun() Colour {        return new3 ("Lehmbraun",        115,  59,  36) }
func Kupferbraun() Colour {      return new3 ("Kupferbraun",      133,  56,  43) }
func Rehbraun() Colour {         return new3 ("Rehbraun",          94,  51,  31) }
func Olivbraun() Colour {        return new3 ("Olivbraun",         99,  61,  36) }
func Nussbraun() Colour {        return new3 ("Nussbraun",         71,  38,  28) }
func Rotbraun() Colour {         return new3 ("Rotbraun",          84,  31,  31) }
func Sepiabraun() Colour {       return new3 ("Sepiabraun",        56,  38,  28) }
func Kastanienbraun() Colour {   return new3 ("Kastanienbraun",    77,  31,  28) }
func Mahagonibraun() Colour {    return new3 ("Mahagonibraun",     61,  31,  28) }
func Schokoladenbraun() Colour { return new3 ("Schokoladenbraun",  46,  28,  28) }
func Graubraun() Colour {        return new3 ("Graubraun",         43,  38,  41) }
func Schwarzbraun() Colour {     return new3 ("Schwarzbraun",      13,   8,  13) }
func Orangebraun() Colour {      return new3 ("Orangebraun",      156,  69,  41) }
func Beigebraun() Colour {       return new3 ("Beigebraun",       110,  64,  48) }
func Blassbraun() Colour {       return new3 ("Blassbraun",       102,  74,  61) }
func Terrabraun() Colour {       return new3 ("Terrabraun",        64,  46,  33) }
func Cremeweiß() Colour {        return new3 ("Cremeweiß",        255, 252, 240) }
func Grauweiß() Colour {         return new3 ("Grauweiß",         240, 237, 230) }
func Signalweiß() Colour {       return new3 ("Signalweiß",       255, 255, 255) }
func Signalschwarz() Colour {    return new3 ("Signalschwarz",     28,  28,  33) }
func Tiefschwarz() Colour {      return new3 ("Tiefschwarz",        3,   5,  10) }
func Aluminiumweiß() Colour {    return new3 ("Aluminiumweiß",    166, 171, 181) }
func Aluminiumgrau() Colour {    return new3 ("Aluminiumgrau",    125, 122, 120) }
func Reinweiß() Colour {         return new3 ("Reinweiß",         250, 255, 255) }
func Graphitschwarz() Colour {   return new3 ("Graphitschwarz",    13,  18,  26) }
func Verkehrsweiß() Colour {     return new3 ("Verkehrsweiß",     252, 255, 255) }
func Verkehrsschwarz() Colour {  return new3 ("Verkehrsschwarz",   20,  23,  28) }
func Papyrusweiß() Colour {      return new3 ("Papyrusweiß",      219, 227, 222) }
