package col

// (c) Christian Maurer   v. 191105 - license see µU.go

func Grünbeige() Colour {        return new3 ("grünbeige",        214, 199, 148) }
func Beige() Colour {            return new3 ("beige",            217, 186, 140) }
func Sandgelb() Colour {         return new3 ("sandgelb",         214, 176, 117) }
func Signalgelb() Colour {       return new3 ("signalgelb ",      252, 163,  41) }
func Goldgelb() Colour {         return new3 ("goldgelb",         227, 150,  36) }
func Honiggelb() Colour {        return new3 ("honiggelb",        201, 135,  33) }
func Maisgelb() Colour {         return new3 ("maisgelb",         224, 130,  31) }
func Narzissengelb() Colour {    return new3 ("narzissengelb",    227, 122,  31) }
func Braunbeige() Colour {       return new3 ("braunbeige",       173, 122,  79) }
func Zitronengelb() Colour {     return new3 ("zitronengelb",     227, 184,  56) }
func Perlweiß() Colour {         return new3 ("perlweiß",         255, 245, 227) }
func Elfenbein() Colour {        return new3 ("elfenbein",        240, 214, 171) }
func Hellelfenbein() Colour {    return new3 ("hellelfenbein",    252, 235, 204) }
func Schwefelgelb() Colour {     return new3 ("schwefelgelb",     255, 245,  66) }
func Safrangelb() Colour {       return new3 ("safrangelb",       255, 171,  89) }
func Zinkgelb() Colour {         return new3 ("zinkgelb",         255, 214,  77) }
func Graubeige() Colour {        return new3 ("graubeige",        163, 140, 122) }
func Olivgelb() Colour {         return new3 ("olivgelb",         156, 143,  97) }
func Rapsgelb() Colour {         return new3 ("rapsgelb",         252, 189,  31) }
func Verkehrsgelb() Colour {     return new3 ("verkehrsgelb",     252, 184,  33) }
func Ockergelb() Colour {        return new3 ("ockergelb",        181, 140,  79) }
func Leuchtgelb() Colour {       return new3 ("leuchtgelb",       255, 255,  10) }
func Currygelb() Colour {        return new3 ("currygelb",        153, 117,  33) }
func Melonengelb() Colour {      return new3 ("melonengelb",      255, 140,  26) }
func Ginstergelb() Colour {      return new3 ("ginstergelb",      227, 163,  41) }
func Dahliengelb() Colour {      return new3 ("dahliengelb",      255, 148,  54) }
func Pastellgelb() Colour {      return new3 ("pastellgelb",      247, 153,  92) }
func Gelborange() Colour {       return new3 ("gelborange",       224,  94,  31) }
func Rotorange() Colour {        return new3 ("rotorange",        186,  46,  33) }
func Blutorange() Colour {       return new3 ("blutorange",       204,  36,  28) }
func Pastellorange() Colour {    return new3 ("pastellorange",    255,  99,  54) }
func Reinorange() Colour {       return new3 ("reinorange",       242,  59,  28) }
func Leuchtorange() Colour {     return new3 ("leuchtorange",     252,  28,  20) }
func Leuchthellorange() Colour { return new3 ("leuchthellorange", 255, 117,  33) }
func Hellrotorange() Colour {    return new3 ("hellrotorange",    250,  79,  41) }
func Verkehrsorange() Colour {   return new3 ("verkehrsorange",   235,  59,  28) }
func Signalorange() Colour {     return new3 ("signalorange",     212,  69,  41) }
func Tieforange() Colour {       return new3 ("tieforange",       237,  92,  41) }
func Lachsorange() Colour {      return new3 ("lachsorange",      222,  82,  71) }
func Feuerrot() Colour {         return new3 ("feuerrot",         171,  31,  28) }
func Signalrot() Colour {        return new3 ("signalrot",        163,  23,  26) }
func Karminrot() Colour {        return new3 ("karminrot",        163,  26,  26) }
func Rubinrot() Colour {         return new3 ("rubinrot",         138,  18,  20) }
func Purpurrot() Colour {        return new3 ("purpurrot",        105,  15,  20) }
func Weinrot() Colour {          return new3 ("weinrot",           79,  18,  26) }
func Schwarzrot() Colour {       return new3 ("schwarzrot",        46,  18,  26) }
func Oxidrot() Colour {          return new3 ("oxidrot",           94,  33,  33) }
func Braunrot() Colour {         return new3 ("braunrot",         120,  20,  23) }
func Beigerot() Colour {         return new3 ("beigerot",         204, 130, 115) }
func Tomatenrot() Colour {       return new3 ("tomatenrot",       150,  31,  28) }
func Altrosa() Colour {          return new3 ("altrosa",          217, 102, 117) }
func Hellrosa() Colour {         return new3 ("hellrosa",         232, 156, 181) }
func Korallenrot() Colour {      return new3 ("korallenrot",      166,  36,  38) }
func Rose() Colour {             return new3 ("rose",             209,  54,  84) }
func Erdbeerrot() Colour {       return new3 ("erdbeerrot",       207,  41,  66) }
func Verkehrsrot() Colour {      return new3 ("verkehrsrot",      199,  23,  18) }
func Lachsrot() Colour {         return new3 ("lachsrot",         217,  89,  79) }
func Leuchtrot() Colour {        return new3 ("leuchtrot",        252,  10,  28) }
func Leuchthellrot() Colour {    return new3 ("leuchthellrot",    252,  20,  20) }
func Himbeerrot() Colour {       return new3 ("himbeerrot",       181,  18,  51) }
func Orientrot() Colour {        return new3 ("orientrot",        166,  28,  46) }
func Rotlila() Colour {          return new3 ("rotlila",          130,  64, 128) }
func Rotmagenta() Colour {       return new3 ("rotmagenta",       143,  38,  64) }
func Erikamagenta() Colour {     return new3 ("erikamagenta",     201,  56, 140) }
func Bordeauxmagenta() Colour {  return new3 ("bordeauxmagenta",   92,   8,  43) }
func Blaulila() Colour {         return new3 ("blaulila",          99,  61, 156) }
func Verkehrspurpur() Colour {   return new3 ("verkehrspurpur",   145,  15, 102) }
func Purpurmagenta() Colour {    return new3 ("purpurmagenta",     56,  10,  46) }
func Signalviolett() Colour {    return new3 ("signalviolett",    125,  31, 122) }
func Pastellviolett() Colour {   return new3 ("pastellviolett",   158, 115, 148) }
func Telemagenta() Colour {      return new3 ("telemagenta",      191,  23, 115) }
func Violettblau() Colour {      return new3 ("violettblau",       23,  51, 107) }
func Grünblau() Colour {         return new3 ("grünblau",          10,  51,  84) }
func Ultramarinblau() Colour {   return new3 ("ultramarinblau",     0,  15, 117) }
func Saphirblau() Colour {       return new3 ("saphirblau",         0,  23,  69) }
func Schwarzblau() Colour {      return new3 ("schwarzblau",        3,  13,  31) }
func Signalblau() Colour {       return new3 ("signalblau",         0,  46, 122) }
func Brillantblau() Colour {     return new3 ("brillantblau",      38,  79, 135) }
func Graublau() Colour {         return new3 ("graublau",          26,  41,  56) }
func Azurblau() Colour {         return new3 ("azurblau",          23,  69, 112) }
func Enzianblau() Colour {       return new3 ("enzianblau",         0,  43, 112) }
func Stahlblau() Colour {        return new3 ("stahlblau",          3,  20,  46) }
func Lichtblau() Colour {        return new3 ("lichtblau",         41, 115, 184) }
func Kobaltblau() Colour {       return new3 ("kobaltblau",         0,  18,  69) }
func Taubenblau() Colour {       return new3 ("taubenblau",        77, 105, 153) }
func Himmelblau() Colour {       return new3 ("himmelblau",        23,  97, 171) }
func Verkehrsblau() Colour {     return new3 ("verkehrsblau",       0,  59, 128) }
func Türkisblau() Colour {       return new3 ("türkisblau",        56, 148, 130) }
func Capriblau() Colour {        return new3 ("capriblau",         10,  66, 120) }
func Ozeanblau() Colour {        return new3 ("ozeanblau",          5,  51,  51) }
func Wasserblau() Colour {       return new3 ("wasserblau",        26, 122,  99) }
func Nachtblau() Colour {        return new3 ("nachtblau",          0,   8,  79) }
func Fernblau() Colour {         return new3 ("fernblau",          46,  82, 143) }
func Pastellblau() Colour {      return new3 ("pastellblau",       87, 140, 181) }
func Patinagrün() Colour {       return new3 ("patinagrün",        51, 120,  84) }
func Smaragdgrün() Colour {      return new3 ("smaragdgrün",       38, 102,  41) }
func Laubgrün() Colour {         return new3 ("laubgrün",          38,  87,  33) }
func Olivgrün() Colour {         return new3 ("olivgrün",          61,  69,  46) }
func Blaugrün() Colour {         return new3 ("blaugrün",          13,  59,  46) }
func Moosgrün() Colour {         return new3 ("moosgrün",          10,  56,  31) }
func Grauoliv() Colour {         return new3 ("grauoliv",          41,  43,  36) }
func Flaschengrün() Colour {     return new3 ("flaschengrün",      28,  38,  23) }
func Braungrün() Colour {        return new3 ("braungrün",         33,  33,  26) }
func Tannengrün() Colour {       return new3 ("tannengrün",        23,  41,  28) }
func Grasgrün() Colour {         return new3 ("grasgrün",          54, 105,  38) }
func Resedagrün() Colour {       return new3 ("resedagrün",        94, 125,  79) }
func Schwarzgrün() Colour {      return new3 ("schwarzgrün",       31,  46,  43) }
func Schilfgrün() Colour {       return new3 ("schilfgrün",       117, 115,  79) }
func Gelboliv() Colour {         return new3 ("gelboliv",          51,  48,  38) }
func Schwarzoliv() Colour {      return new3 ("schwarzoliv",       41,  43,  38) }
func Cyangrün() Colour {         return new3 ("cyangrün",          15, 112,  51) }
func Maigrün() Colour {          return new3 ("maigrün",           64, 130,  54) }
func Gelbgrün() Colour {         return new3 ("gelbgrün",          79, 168,  51) }
func Weißgrün() Colour {         return new3 ("weißgrün",         191, 227, 186) }
func Chromoxidgrün() Colour {    return new3 ("chromoxidgrün",     38,  56,  41) }
func Blassgrün() Colour {        return new3 ("blassgrün",        133, 166, 122) }
func Braunoliv() Colour {        return new3 ("braunoliv",         43,  38,  28) }
func Verkehrsgrün() Colour {     return new3 ("verkehrsgrün",      36, 145,  64) }
func Farngrün() Colour {         return new3 ("farngrün",          74, 110,  51) }
func Opalgrün() Colour {         return new3 ("opalgrün",          10,  92,  51) }
func Lichtgrün() Colour {        return new3 ("lichtgrün",        125, 204, 189) }
func Kieferngrün() Colour {      return new3 ("kieferngrün",       38,  74,  51) }
func Minzgrün() Colour {         return new3 ("minzgrün",          18, 120,  38) }
func Signalgrün() Colour {       return new3 ("signalgrün",        41, 138,  64) }
func Minttürkis() Colour {       return new3 ("minttürkis",        66, 140, 120) }
func Pastelltürkis() Colour {    return new3 ("pastelltürkis",      0,   0,   0) } // XXX falsch
func Fehgrau() Colour {          return new3 ("fehgrau",          115, 133, 145) }
func Silbergrau() Colour {       return new3 ("silbergrau",       135, 148, 166) }
func Olivgrau() Colour {         return new3 ("olivgrau",         122, 117,  97) }
func Moosgrau() Colour {         return new3 ("moosgrau",         112, 112,  97) }
func Signalgrau() Colour {       return new3 ("signalgrau",       156, 156, 166) }
func Mausgrau() Colour {         return new3 ("mausgrau",          97, 105, 105) }
func Beigegrau() Colour {        return new3 ("beigegrau",        107,  97,  87) }
func Khakigrau() Colour {        return new3 ("khakigrau",        105,  84,  56) }
func Grüngrau() Colour {         return new3 ("grüngrau",          77,  82,  74) }
func Zeltgrau() Colour {         return new3 ("zeltgrau",          74,  79,  74) }
func Eisengrau() Colour {        return new3 ("eisengrau",         64,  74,  84) }
func Basaltgrau() Colour {       return new3 ("basaltgrau",        74,  84,  89) }
func Braungrau() Colour {        return new3 ("braungrau",         71,  66,  56) }
func Schiefergrau() Colour {     return new3 ("schiefergrau",      61,  66,  82) }
func Anthrazitgrau() Colour {    return new3 ("anthrazitgrau",     38,  46,  56) }
func Schwarzgrau() Colour {      return new3 ("schwarzgrau",       26,  33,  41) }
func Umbragrau() Colour {        return new3 ("umbragrau",         61,  61,  59) }
func Betongrau() Colour {        return new3 ("betongrau",        122, 125, 117) }
func Graphitgrau() Colour {      return new3 ("graphitgrau",       48,  56,  69) }
func Granitgrau() Colour {       return new3 ("granitgrau",        38,  51,  56) }
func Steingrau() Colour {        return new3 ("steingrau",        145, 143, 135) }
func Blaugrau() Colour {         return new3 ("blaugrau",          77,  92, 107) }
func Kieselgrau() Colour {       return new3 ("kieselgrau",       189, 186, 171) }
func Zementgrau() Colour {       return new3 ("zementgrau",       122, 130, 117) }
func Gelbgrau() Colour {         return new3 ("gelbgrau",         143, 135, 112) }
func Lichtgrau() Colour {        return new3 ("lichtgrau",        212, 217, 219) }
func Platingrau() Colour {       return new3 ("platingrau",       158, 150, 156) }
func Staubgrau() Colour {        return new3 ("staubgrau",        122, 125, 128) }
func Achatgrau() Colour {        return new3 ("achatgrau",        186, 189, 186) }
func Quarzgrau() Colour {        return new3 ("quarzgrau",         97,  94,  89) }
func Fenstergrau() Colour {      return new3 ("fenstergrau",      158, 163, 176) }
func VerkehrsgrauA() Colour {    return new3 ("verkehrsgrauA",    143, 150, 153) }
func VerkehrsgrauB() Colour {    return new3 ("verkehrsgrauB",     64,  69,  69) }
func Seidengrau() Colour {       return new3 ("seidengrau",       194, 191, 184) }
func Telegrau1() Colour {        return new3 ("telegrau1",        143, 148, 158) }
func Telegrau2() Colour {        return new3 ("telegrau2",        120, 130, 140) }
func Telegrau4() Colour {        return new3 ("telegrau4",        217, 214, 219) }
func Grünbraun() Colour {        return new3 ("grünbraun",        125,  92,  56) }
func Ockerbraun() Colour {       return new3 ("ockerbraun",       145,  82,  46) }
func Signalbraun() Colour {      return new3 ("signalbraun",      110,  59,  48) }
func Lehmbraun() Colour {        return new3 ("lehmbraun",        115,  59,  36) }
func Kupferbraun() Colour {      return new3 ("kupferbraun",      133,  56,  43) }
func Rehbraun() Colour {         return new3 ("rehbraun",          94,  51,  31) }
func Olivbraun() Colour {        return new3 ("olivbraun",         99,  61,  36) }
func Nussbraun() Colour {        return new3 ("nussbraun",         71,  38,  28) }
func Rotbraun() Colour {         return new3 ("rotbraun",          84,  31,  31) }
func Sepiabraun() Colour {       return new3 ("sepiabraun",        56,  38,  28) }
func Kastanienbraun() Colour {   return new3 ("kastanienbraun",    77,  31,  28) }
func Mahagonibraun() Colour {    return new3 ("mahagonibraun",     61,  31,  28) }
func Schokoladenbraun() Colour { return new3 ("schokoladenbraun",  46,  28,  28) }
func Graubraun() Colour {        return new3 ("graubraun",         43,  38,  41) }
func Schwarzbraun() Colour {     return new3 ("schwarzbraun",      13,   8,  13) }
func Orangebraun() Colour {      return new3 ("orangebraun",      156,  69,  41) }
func Beigebraun() Colour {       return new3 ("beigebraun",       110,  64,  48) }
func Blassbraun() Colour {       return new3 ("blassbraun",       102,  74,  61) }
func Terrabraun() Colour {       return new3 ("terrabraun",        64,  46,  33) }
func Cremeweiß() Colour {        return new3 ("cremeweiß",        255, 252, 240) }
func Grauweiß() Colour {         return new3 ("grauweiß",         240, 237, 230) }
func Signalweiß() Colour {       return new3 ("signalweiß",       255, 255, 255) }
func Signalschwarz() Colour {    return new3 ("signalschwarz",     28,  28,  33) }
func Tiefschwarz() Colour {      return new3 ("tiefschwarz",        3,   5,  10) }
func Aluminiumweiß() Colour {    return new3 ("aluminiumweiß",    166, 171, 181) }
func Aluminiumgrau() Colour {    return new3 ("aluminiumgrau",    125, 122, 120) }
func Reinweiß() Colour {         return new3 ("reinweiß",         250, 255, 255) }
func Graphitschwarz() Colour {   return new3 ("graphitschwarz",    13,  18,  26) }
func Verkehrsweiß() Colour {     return new3 ("verkehrsweiß",     252, 255, 255) }
func Verkehrsschwarz() Colour {  return new3 ("verkehrsschwarz",   20,  23,  28) }
func Papyrusweiß() Colour {      return new3 ("papyrusweiß",      219, 227, 222) }
